version: '3.8'
services:
  backend:
    build:
      context: ./server
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build:
      context: ./client
    ports:
      - "8080:80"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: roomrover
      POSTGRES_USER: roomrover
      POSTGRES_PASSWORD: roomrover
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
